### ISSUE TITLE
Can't access file resource from network context

### ISSUE THREAD

**Issue by aecollver** [hyperjump-io/json-schema-core#1]
I'm trying to load a schema from a file:

```
import { get } from "@hyperjump/json-schema/lib";
import { join } from "path";

const schema = await get("file://" + join(__dirname, "mySchema.json"));

```

I expected this to work based on the example in the readme, but I get this error message:

```
{
  "message": "Can't access file resource from network context",
  "stack": [
    "Error: Can't access file resource from network context",
    "    at safeResolveUrl (/var/task/node_modules/@hyperjump/json-schema-core/lib/schema.js:184:11)",
    "    at Object.get (/var/task/node_modules/@hyperjump/json-schema-core/lib/schema.js:135:23)",
    "    at Resource.doMove (/var/src/api/target-resource.ts:113:26)",
    "    at Resource.handle (/var/src/api/target-resource.ts:48:21)",
    "    at Object.handleProxyEvent (/var/src/api/index.ts:11:37)",
    "    at Runtime.handler (/var/src/application.ts:11:12)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

Am I doing something wrong?

**Comment by jdesrosiers** [comment]
I just published the fix. Please try it out and let me know if it's working for you.

NOTE: The bug was in json-schema-core, not in json-schema-validator where the bug was reported, so when you update you should expect to see a version bump in the json-schema-core dependency.

**Comment by aecollver** [comment]
Thank you for fixing this!
